### ISSUE TITLE
Unable to download VR Weapon Overhaul Fixes.7z

### ISSUE THREAD

**Issue by WJSchultz25** [ajantaju/F4FEVR#3]
Hopefully that's pretty self explanatory.  Wabbajack apparently cannot locate the file.  I'll continue on given that's the only problem I'm running into and see if everything still runs fine, but if not I at least have this much documented.

**Comment by WJSchultz25** [comment]
Quick easy fix, but if anyone else has the issue just pull it manually from the Git.

**Comment by ajantaju** [comment]
Fixed. File is now hosted in Wabbajack Content Delivery Network.

**Comment by ajantaju** [comment]
I had bad link in the meta file. Files hosted at github again.
